// <auto-generated />
using System;
using InsurgencyAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsurgencyAPI.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20241205165408_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("InsurgencyAPI.Models.Arma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Alcance")
                        .HasColumnType("REAL");

                    b.Property<int?>("ClasseId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Dano")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.ToTable("Armas");
                });

            modelBuilder.Entity("InsurgencyAPI.Models.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Vida")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("InsurgencyAPI.Models.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClasseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InventarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("InventarioId");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("InsurgencyAPI.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("InsurgencyAPI.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InventarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InventarioId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("InsurgencyAPI.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClasseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("InventarioId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("InsurgencyAPI.Models.Arma", b =>
                {
                    b.HasOne("InsurgencyAPI.Models.Classe", null)
                        .WithMany("ArmasPermitidas")
                        .HasForeignKey("ClasseId");
                });

            modelBuilder.Entity("InsurgencyAPI.Models.Equipamento", b =>
                {
                    b.HasOne("InsurgencyAPI.Models.Classe", null)
                        .WithMany("EquipamentosPermitidos")
                        .HasForeignKey("ClasseId");

                    b.HasOne("InsurgencyAPI.Models.Inventario", null)
                        .WithMany("Equipamentos")
                        .HasForeignKey("InventarioId");
                });

            modelBuilder.Entity("InsurgencyAPI.Models.Item", b =>
                {
                    b.HasOne("InsurgencyAPI.Models.Inventario", null)
                        .WithMany("Itens")
                        .HasForeignKey("InventarioId");
                });

            modelBuilder.Entity("InsurgencyAPI.Models.Persona", b =>
                {
                    b.HasOne("InsurgencyAPI.Models.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsurgencyAPI.Models.Inventario", "Inventario")
                        .WithMany()
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("InsurgencyAPI.Models.Classe", b =>
                {
                    b.Navigation("ArmasPermitidas");

                    b.Navigation("EquipamentosPermitidos");
                });

            modelBuilder.Entity("InsurgencyAPI.Models.Inventario", b =>
                {
                    b.Navigation("Equipamentos");

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
